Don't check for neovim since we're only using neovim, and generate the rplugin manifest globally on update

diff --git a/update b/update
--- a/update
+++ b/update
@@ -261,19 +261,17 @@ type -P vim >/dev/null && {
     fi
 }
 
-### UPDATE REMOTE PLUGINS IN NEOVIM
-type -P nvim >/dev/null && {
-    printf '%s' "$cbg_blue >> Updating remote plugins for neovim:$c_reset"
-    $timeout_command --preserve-status --foreground 1m nvim -u ./init.vim -c ':UpdateRemotePlugins|qa!'
+### UPDATE REMOTE PLUGINS
+printf '%s' "$cbg_blue >> Updating remote plugins for neovim:$c_reset"
+$timeout_command --preserve-status --foreground 1m nvim -u ./init.vim -c ':UpdateRemotePlugins|qa!'
 
-    if (( ! $? )); then
-        printf '%s\n' "$cfg_green_bold SUCCESS! $c_reset"
-    else
-        reset -I
-        printf '%s\n' "$cfg_red_bold FAIL! $c_reset"
-        error "nvim -u ./init.vim -c ':UpdateRemotePlugins|qa!'" 'Updating remote plugins for neovim failed'
-    fi
-}
+if (( ! $? )); then
+    printf '%s\n' "$cfg_green_bold SUCCESS! $c_reset"
+else
+    reset -I
+    printf '%s\n' "$cfg_red_bold FAIL! $c_reset"
+    error "nvim -u ./init.vim -c ':UpdateRemotePlugins|qa!'" 'Updating remote plugins for neovim failed'
+fi
 
 ### FINISH
 printf '\n%s\n\n' "$cbg_black ~~~ Update Complete ~~~ $c_reset"
