Move all local/user files (user.vim, the user bundle directory and rplugin.vim) to a new "local" folder

diff --git a/update b/update
--- a/update
+++ b/update
@@ -8,6 +8,14 @@
 #  Released under the MIT license
 #
 
+#
+# VARIABLES
+#
+
+user_vim_config=local/user.vim
+local_bundle_dir=local/bundle
+error_log=update-errors.log
+
 script_name="${0//*\/}"
 script_home="${0%$script_name}"
 
@@ -18,9 +26,6 @@ else
     script_home="$PWD"
     popd >/dev/null || exit
 fi
-
-repo_version="$(printf "%s.r%s" "$(git show -s --format=%ci master | sed 's/\ .*//g;s/-//g')" "$(git rev-list --count HEAD)")"
-error_log='update-errors.log'
 
 if [[ -t 1 ]]; then
     cbg_blue=$'\e[44m'
@@ -35,6 +40,10 @@ else
     cbg_blue='#'
 fi
 
+#
+# FUNCTIONS
+#
+
 # error: output and log error
 function error {
     printf '%s\n' "$cbg_blue $c_reset$cbg_red_bold ! ERROR: $c_reset$cfg_red_bold $2 " >&2
@@ -47,6 +56,7 @@ function error {
 
 # show_version: displays version information
 function show_version {
+    repo_version="$(printf "%s.r%s" "$(git show -s --format=%ci master | sed 's/\ .*//g;s/-//g')" "$(git rev-list --count HEAD)")"
     printf '%s\n' "$script_name: darkcloud-nvimconfig update tool (version: $repo_version)"
 }
 
@@ -60,7 +70,10 @@ function show_help {
     printf '%s\n' 'Run with no arguments to update darkcloud-nvimconfig'
 }
 
-### SETUP
+#
+# SETUP
+#
+
 if type -P timeout >/dev/null; then
     timeout_command=timeout
 elif type -P gtimeout >/dev/null; then
@@ -98,23 +111,23 @@ cd "$script_home" || exit
 # display script title
 printf '\n%s\n' "$cbg_black ~~~ DarkCloud Neovim Config Update Tool ~~~ $c_reset"
 
-# create vim/bundle.user if it doesn't exist
-[[ -d 'vim/bundle.user' ]] || {
+# create the local bundle directory if it doesn't exist
+[[ -d "$local_bundle_dir" ]] || {
     printf '\n%s' "$cbg_blue >> Creating user plugin directory:$c_reset"
-    process_status="$(install -d 'vim/bundle.user' 2>&1)"
+    process_status="$(install -d "$local_bundle_dir" 2>&1)"
 
     if (( ! $? )); then
         printf '%s\n' "$cfg_green_bold SUCCESS! $c_reset"
     else
         printf '%s\n' "$cfg_red_bold FAIL! $c_reset"
-        error 'install -d vim/bundle.user' "User plugin directory couldn't be created" "$process_status"
+        error "install -d $local_bundle_dir" "User plugin directory couldn't be created" "$process_status"
     fi
 }
 
-# create vim/user.vim if it doesn't exist
-[[ -e 'vim/user.vim' ]] || {
+# create user.vim if it doesn't exist
+[[ -e "$user_vim_config" ]] || {
     printf '\n%s' "$cbg_blue >> Creating user config file:$c_reset"
-    process_status="$(touch 'vim/user.vim' 2>&1)"
+    process_status="$(touch "$user_vim_config" 2>&1)"
 
     if (( ! $? )); then
         {
@@ -124,20 +137,23 @@ printf '\n%s\n' "$cbg_black ~~~ DarkCloud Neovim Config Update Tool ~~~ $c_reset
             printf '%s\n%s\n\n' '"Enable Auto-completion: (1:autocompletion enabled | *0:autocompletion disabled)' '"let g:enablecompletion = 1'
             printf '%s\n%s\n\n' '"Enable automatic tag generation: (1:enable tag generation | *0:disable automatic tag generation)' '"let g:enableautotags = 1'
             printf '%s\n%s\n'   '"Enable Powerline: (1:use powerline characters | *0:use regular characters)' '"let g:enablepowerline = 1'
-        } >> vim/user.vim
+        } >> "$user_vim_config"
 
-        if [[ -e 'vim/user.vim' ]]; then
+        if [[ -e "$user_vim_config" ]]; then
             printf '%s\n' "$cfg_green_bold SUCCESS! $c_reset"
         else
             printf '%s\n' "$cfg_red_bold FAIL! $c_reset"
         fi
     else
         printf '%s\n' "$cfg_red_bold FAIL! $c_reset"
-        error "touch vim/user.vim" "User config couldn't be created" "$process_status"
+        error "touch $user_vim_config" "User config couldn't be created" "$process_status"
     fi
 }
 
-### REPO UPDATE
+#
+# REPO UPDATE
+#
+
 printf '\n%s' "$cbg_blue >> Updating darkcloud-nvimconfig:$c_reset"
 process_status="$(git pull origin master 2>&1)"
 
@@ -149,7 +165,10 @@ else
     exit 1
 fi
 
-### SUBMODULE UPDATE {
+#
+# SUBMODULE UPDATE
+#
+
 printf '\n%s\n' "$cbg_blue >> Updating plugin submodules >> $c_reset"
 printf '%s' "$cbg_blue $c_reset$cbg_yellow + Updating plugin URLs:$c_reset"
 process_status="$(git submodule sync 2>&1)"
@@ -218,15 +237,18 @@ fi
     printf '\n'
 }
 
-### USER PLUGIN UPDATE
-[[ -d vim/bundle.user ]] && find vim/bundle.user -mindepth 3 -maxdepth 3 -name config | grep -q '.git/config' && {
+#
+# USER PLUGIN UPDATE
+#
+
+[[ -d "$local_bundle_dir" ]] && find "$local_bundle_dir" -mindepth 3 -maxdepth 3 -name config | grep -q '.git/config' && {
     printf '%s\n' "$cbg_blue >> Updating user plugins >> $c_reset"
-    pushd 'vim/bundle.user' >/dev/null || exit
+    pushd "$local_bundle_dir" >/dev/null || exit
 
     for plugin in *; do
         [[ -d "$plugin/.git" ]] && {
             pushd "$plugin" >/dev/null || exit
-            printf '%s' "$cbg_blue $c_reset$cbg_yellow + Updating 'vim/bundle.user/$plugin':$c_reset"
+            printf '%s' "$cbg_blue $c_reset$cbg_yellow + Updating '$local_bundle_dir/$plugin':$c_reset"
             process_status="$(git pull 2>&1)"
 
             if (( ! $? )); then
@@ -247,7 +269,10 @@ fi
     printf '\n'
 }
 
-### GENERATE PLUGIN HELP
+#
+# GENERATE PLUGIN HELP
+#
+
 type -P vim >/dev/null && {
     printf '%s' "$cbg_blue >> Generating plugin help:$c_reset"
     $timeout_command --preserve-status --foreground 1m nvim -c 'Helptags|qa!'
@@ -261,7 +286,10 @@ type -P vim >/dev/null && {
     fi
 }
 
-### UPDATE REMOTE PLUGINS
+#
+# UPDATE REMOTE PLUGINS
+#
+
 printf '%s' "$cbg_blue >> Updating remote plugins for neovim:$c_reset"
 $timeout_command --preserve-status --foreground 1m nvim -c ':UpdateRemotePlugins|qa!'
 
@@ -273,5 +301,8 @@ else
     error "nvim -c ':UpdateRemotePlugins|qa!'" 'Updating remote plugins for neovim failed'
 fi
 
-### FINISH
+#
+# FINISH
+#
+
 printf '\n%s\n\n' "$cbg_black ~~~ Update Complete ~~~ $c_reset"
